//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yyx.BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public string OrderItemID { get; set; }
        public string OrderID { get; set; }
        public string StoreID { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal ActualAmount { get; set; }
        public string PayStatusID { get; set; }
        public bool DelStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdatDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
