//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yyx.BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderComment = new HashSet<OrderComment>();
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public string OrderID { get; set; }
        public string OrderNo { get; set; }
        public string UserID { get; set; }
        public string UserAddressID { get; set; }
        public string StoreID { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public string OrderStatusID { get; set; }
        public string PayStatusID { get; set; }
        public string OrderMemo { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public bool DelStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual ICollection<OrderComment> OrderComment { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
