//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yyx.BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PaymentID { get; set; }
        public string OrderID { get; set; }
        public string PaymentNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal ActualAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentTypeID { get; set; }
        public string PayStatusID { get; set; }
        public string FromAccountID { get; set; }
        public string ToAccountID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string TransationID { get; set; }
        public string Memo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual PayStatus PayStatus { get; set; }
    }
}
