//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yyx.BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.StoreProduct = new HashSet<StoreProduct>();
            this.StoreOperator = new HashSet<StoreOperator>();
        }
    
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string AccountID { get; set; }
        public string CityID { get; set; }
        public string WorkArea { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public bool DelStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<StoreProduct> StoreProduct { get; set; }
        public virtual ICollection<StoreOperator> StoreOperator { get; set; }
    }
}
