//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yyx.BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserAddress = new HashSet<UserAddress>();
        }
    
        public string UserID { get; set; }
        public string AccountID { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Gender { get; set; }
        public string HeadImagePath { get; set; }
        public string CellPhone { get; set; }
        public string PassWord { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool DelStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<UserAddress> UserAddress { get; set; }
    }
}
